// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Anf.WebService
{
    [DbContext(typeof(AnfDbContext))]
    public partial class AnfDbContextModel : RuntimeModel
    {
        static AnfDbContextModel()
        {
            var model = new AnfDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static AnfDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
