// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Anf.WebService
{
    public partial class AnfDbContextModel
    {
        partial void Initialize()
        {
            var anfApp = AnfAppEntityType.Create(this);
            var anfBookshelf = AnfBookshelfEntityType.Create(this);
            var anfBookshelfItem = AnfBookshelfItemEntityType.Create(this);
            var anfComicSearch = AnfComicSearchEntityType.Create(this);
            var anfComicVisit = AnfComicVisitEntityType.Create(this);
            var anfRole = AnfRoleEntityType.Create(this);
            var anfSearchStatistic = AnfSearchStatisticEntityType.Create(this);
            var anfUser = AnfUserEntityType.Create(this);
            var anfVisitStatistic = AnfVisitStatisticEntityType.Create(this);
            var anfWord = AnfWordEntityType.Create(this);
            var anfWordLike = AnfWordLikeEntityType.Create(this);
            var anfWordReadCount = AnfWordReadCountEntityType.Create(this);
            var anfWordUpdateCount = AnfWordUpdateCountEntityType.Create(this);
            var anfWordUserCount = AnfWordUserCountEntityType.Create(this);
            var anfWordVisit = AnfWordVisitEntityType.Create(this);
            var hQueryStatistic = HQueryStatisticEntityType.Create(this);
            var kvComicChapter = KvComicChapterEntityType.Create(this);
            var kvComicEntity = KvComicEntityEntityType.Create(this);
            var identityRoleClaimlong = IdentityRoleClaimlongEntityType.Create(this);
            var identityUserClaimlong = IdentityUserClaimlongEntityType.Create(this);
            var identityUserLoginlong = IdentityUserLoginlongEntityType.Create(this);
            var identityUserRolelong = IdentityUserRolelongEntityType.Create(this);
            var identityUserTokenlong = IdentityUserTokenlongEntityType.Create(this);

            AnfAppEntityType.CreateForeignKey1(anfApp, anfUser);
            AnfBookshelfEntityType.CreateForeignKey1(anfBookshelf, anfBookshelf);
            AnfBookshelfEntityType.CreateForeignKey2(anfBookshelf, anfUser);
            AnfBookshelfItemEntityType.CreateForeignKey1(anfBookshelfItem, anfBookshelf);
            AnfBookshelfItemEntityType.CreateForeignKey2(anfBookshelfItem, anfUser);
            AnfWordEntityType.CreateForeignKey1(anfWord, anfUser);
            AnfWordEntityType.CreateForeignKey2(anfWord, anfUser);
            AnfWordLikeEntityType.CreateForeignKey1(anfWordLike, anfUser);
            AnfWordLikeEntityType.CreateForeignKey2(anfWordLike, anfWord);
            AnfWordReadCountEntityType.CreateForeignKey1(anfWordReadCount, anfUser);
            AnfWordReadCountEntityType.CreateForeignKey2(anfWordReadCount, anfWord);
            AnfWordUserCountEntityType.CreateForeignKey1(anfWordUserCount, anfUser);
            AnfWordVisitEntityType.CreateForeignKey1(anfWordVisit, anfUser);
            AnfWordVisitEntityType.CreateForeignKey2(anfWordVisit, anfWord);
            KvComicChapterEntityType.CreateForeignKey1(kvComicChapter, kvComicEntity);
            IdentityRoleClaimlongEntityType.CreateForeignKey1(identityRoleClaimlong, anfRole);
            IdentityUserClaimlongEntityType.CreateForeignKey1(identityUserClaimlong, anfUser);
            IdentityUserLoginlongEntityType.CreateForeignKey1(identityUserLoginlong, anfUser);
            IdentityUserRolelongEntityType.CreateForeignKey1(identityUserRolelong, anfRole);
            IdentityUserRolelongEntityType.CreateForeignKey2(identityUserRolelong, anfUser);
            IdentityUserTokenlongEntityType.CreateForeignKey1(identityUserTokenlong, anfUser);

            AnfAppEntityType.CreateAnnotations(anfApp);
            AnfBookshelfEntityType.CreateAnnotations(anfBookshelf);
            AnfBookshelfItemEntityType.CreateAnnotations(anfBookshelfItem);
            AnfComicSearchEntityType.CreateAnnotations(anfComicSearch);
            AnfComicVisitEntityType.CreateAnnotations(anfComicVisit);
            AnfRoleEntityType.CreateAnnotations(anfRole);
            AnfSearchStatisticEntityType.CreateAnnotations(anfSearchStatistic);
            AnfUserEntityType.CreateAnnotations(anfUser);
            AnfVisitStatisticEntityType.CreateAnnotations(anfVisitStatistic);
            AnfWordEntityType.CreateAnnotations(anfWord);
            AnfWordLikeEntityType.CreateAnnotations(anfWordLike);
            AnfWordReadCountEntityType.CreateAnnotations(anfWordReadCount);
            AnfWordUpdateCountEntityType.CreateAnnotations(anfWordUpdateCount);
            AnfWordUserCountEntityType.CreateAnnotations(anfWordUserCount);
            AnfWordVisitEntityType.CreateAnnotations(anfWordVisit);
            HQueryStatisticEntityType.CreateAnnotations(hQueryStatistic);
            KvComicChapterEntityType.CreateAnnotations(kvComicChapter);
            KvComicEntityEntityType.CreateAnnotations(kvComicEntity);
            IdentityRoleClaimlongEntityType.CreateAnnotations(identityRoleClaimlong);
            IdentityUserClaimlongEntityType.CreateAnnotations(identityUserClaimlong);
            IdentityUserLoginlongEntityType.CreateAnnotations(identityUserLoginlong);
            IdentityUserRolelongEntityType.CreateAnnotations(identityUserRolelong);
            IdentityUserTokenlongEntityType.CreateAnnotations(identityUserTokenlong);

            AddAnnotation("ProductVersion", "6.0.5");
        }
    }
}
