// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Anf.WebService
{
    public partial class AnfDbContextModel
    {
        partial void Initialize()
        {
            var anfBookshelf = AnfBookshelfEntityType.Create(this);
            var anfBookshelfItem = AnfBookshelfItemEntityType.Create(this);
            var anfDayComicRank = AnfDayComicRankEntityType.Create(this);
            var anfHourComicRank = AnfHourComicRankEntityType.Create(this);
            var anfMonthComicRank = AnfMonthComicRankEntityType.Create(this);
            var anfRole = AnfRoleEntityType.Create(this);
            var anfUser = AnfUserEntityType.Create(this);
            var kvComicChapter = KvComicChapterEntityType.Create(this);
            var kvComicEntity = KvComicEntityEntityType.Create(this);
            var identityRoleClaimlong = IdentityRoleClaimlongEntityType.Create(this);
            var identityUserClaimlong = IdentityUserClaimlongEntityType.Create(this);
            var identityUserLoginlong = IdentityUserLoginlongEntityType.Create(this);
            var identityUserRolelong = IdentityUserRolelongEntityType.Create(this);
            var identityUserTokenlong = IdentityUserTokenlongEntityType.Create(this);

            AnfBookshelfEntityType.CreateForeignKey1(anfBookshelf, anfBookshelf);
            AnfBookshelfEntityType.CreateForeignKey2(anfBookshelf, anfUser);
            AnfBookshelfItemEntityType.CreateForeignKey1(anfBookshelfItem, anfBookshelf);
            AnfBookshelfItemEntityType.CreateForeignKey2(anfBookshelfItem, anfUser);
            KvComicChapterEntityType.CreateForeignKey1(kvComicChapter, kvComicEntity);
            IdentityRoleClaimlongEntityType.CreateForeignKey1(identityRoleClaimlong, anfRole);
            IdentityUserClaimlongEntityType.CreateForeignKey1(identityUserClaimlong, anfUser);
            IdentityUserLoginlongEntityType.CreateForeignKey1(identityUserLoginlong, anfUser);
            IdentityUserRolelongEntityType.CreateForeignKey1(identityUserRolelong, anfRole);
            IdentityUserRolelongEntityType.CreateForeignKey2(identityUserRolelong, anfUser);
            IdentityUserTokenlongEntityType.CreateForeignKey1(identityUserTokenlong, anfUser);

            AnfBookshelfEntityType.CreateAnnotations(anfBookshelf);
            AnfBookshelfItemEntityType.CreateAnnotations(anfBookshelfItem);
            AnfDayComicRankEntityType.CreateAnnotations(anfDayComicRank);
            AnfHourComicRankEntityType.CreateAnnotations(anfHourComicRank);
            AnfMonthComicRankEntityType.CreateAnnotations(anfMonthComicRank);
            AnfRoleEntityType.CreateAnnotations(anfRole);
            AnfUserEntityType.CreateAnnotations(anfUser);
            KvComicChapterEntityType.CreateAnnotations(kvComicChapter);
            KvComicEntityEntityType.CreateAnnotations(kvComicEntity);
            IdentityRoleClaimlongEntityType.CreateAnnotations(identityRoleClaimlong);
            IdentityUserClaimlongEntityType.CreateAnnotations(identityUserClaimlong);
            IdentityUserLoginlongEntityType.CreateAnnotations(identityUserLoginlong);
            IdentityUserRolelongEntityType.CreateAnnotations(identityUserRolelong);
            IdentityUserTokenlongEntityType.CreateAnnotations(identityUserTokenlong);

            AddAnnotation("ProductVersion", "6.0.5");
        }
    }
}
