// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Anf.WebService
{
    public partial class AnfDbContextModel
    {
        partial void Initialize()
        {
            var anfApp = AnfAppEntityType.Create(this);
            var anfBookshelf = AnfBookshelfEntityType.Create(this);
            var anfBookshelfItem = AnfBookshelfItemEntityType.Create(this);
            var anfComicSearch = AnfComicSearchEntityType.Create(this);
            var anfComicSearchRank = AnfComicSearchRankEntityType.Create(this);
            var anfComicVisit = AnfComicVisitEntityType.Create(this);
            var anfComicVisitRank = AnfComicVisitRankEntityType.Create(this);
            var anfRole = AnfRoleEntityType.Create(this);
            var anfUser = AnfUserEntityType.Create(this);
            var hQueryStatistic = HQueryStatisticEntityType.Create(this);
            var hWord = HWordEntityType.Create(this);
            var hWordLike = HWordLikeEntityType.Create(this);
            var hWordReadStatistic = HWordReadStatisticEntityType.Create(this);
            var hWordUpdateStatistic = HWordUpdateStatisticEntityType.Create(this);
            var hWordUserStatistic = HWordUserStatisticEntityType.Create(this);
            var hWordVisit = HWordVisitEntityType.Create(this);
            var kvComicChapter = KvComicChapterEntityType.Create(this);
            var kvComicEntity = KvComicEntityEntityType.Create(this);
            var identityRoleClaimlong = IdentityRoleClaimlongEntityType.Create(this);
            var identityUserClaimlong = IdentityUserClaimlongEntityType.Create(this);
            var identityUserLoginlong = IdentityUserLoginlongEntityType.Create(this);
            var identityUserRolelong = IdentityUserRolelongEntityType.Create(this);
            var identityUserTokenlong = IdentityUserTokenlongEntityType.Create(this);

            AnfAppEntityType.CreateForeignKey1(anfApp, anfUser);
            AnfBookshelfEntityType.CreateForeignKey1(anfBookshelf, anfBookshelf);
            AnfBookshelfEntityType.CreateForeignKey2(anfBookshelf, anfUser);
            AnfBookshelfItemEntityType.CreateForeignKey1(anfBookshelfItem, anfBookshelf);
            AnfBookshelfItemEntityType.CreateForeignKey2(anfBookshelfItem, anfUser);
            AnfComicSearchEntityType.CreateForeignKey1(anfComicSearch, anfUser);
            AnfComicVisitEntityType.CreateForeignKey1(anfComicVisit, anfUser);
            HWordEntityType.CreateForeignKey1(hWord, anfUser);
            HWordEntityType.CreateForeignKey2(hWord, anfUser);
            HWordLikeEntityType.CreateForeignKey1(hWordLike, anfUser);
            HWordLikeEntityType.CreateForeignKey2(hWordLike, hWord);
            HWordReadStatisticEntityType.CreateForeignKey1(hWordReadStatistic, anfUser);
            HWordReadStatisticEntityType.CreateForeignKey2(hWordReadStatistic, hWord);
            HWordUserStatisticEntityType.CreateForeignKey1(hWordUserStatistic, anfUser);
            HWordVisitEntityType.CreateForeignKey1(hWordVisit, anfUser);
            HWordVisitEntityType.CreateForeignKey2(hWordVisit, hWord);
            KvComicChapterEntityType.CreateForeignKey1(kvComicChapter, kvComicEntity);
            IdentityRoleClaimlongEntityType.CreateForeignKey1(identityRoleClaimlong, anfRole);
            IdentityUserClaimlongEntityType.CreateForeignKey1(identityUserClaimlong, anfUser);
            IdentityUserLoginlongEntityType.CreateForeignKey1(identityUserLoginlong, anfUser);
            IdentityUserRolelongEntityType.CreateForeignKey1(identityUserRolelong, anfRole);
            IdentityUserRolelongEntityType.CreateForeignKey2(identityUserRolelong, anfUser);
            IdentityUserTokenlongEntityType.CreateForeignKey1(identityUserTokenlong, anfUser);

            AnfAppEntityType.CreateAnnotations(anfApp);
            AnfBookshelfEntityType.CreateAnnotations(anfBookshelf);
            AnfBookshelfItemEntityType.CreateAnnotations(anfBookshelfItem);
            AnfComicSearchEntityType.CreateAnnotations(anfComicSearch);
            AnfComicSearchRankEntityType.CreateAnnotations(anfComicSearchRank);
            AnfComicVisitEntityType.CreateAnnotations(anfComicVisit);
            AnfComicVisitRankEntityType.CreateAnnotations(anfComicVisitRank);
            AnfRoleEntityType.CreateAnnotations(anfRole);
            AnfUserEntityType.CreateAnnotations(anfUser);
            HQueryStatisticEntityType.CreateAnnotations(hQueryStatistic);
            HWordEntityType.CreateAnnotations(hWord);
            HWordLikeEntityType.CreateAnnotations(hWordLike);
            HWordReadStatisticEntityType.CreateAnnotations(hWordReadStatistic);
            HWordUpdateStatisticEntityType.CreateAnnotations(hWordUpdateStatistic);
            HWordUserStatisticEntityType.CreateAnnotations(hWordUserStatistic);
            HWordVisitEntityType.CreateAnnotations(hWordVisit);
            KvComicChapterEntityType.CreateAnnotations(kvComicChapter);
            KvComicEntityEntityType.CreateAnnotations(kvComicEntity);
            IdentityRoleClaimlongEntityType.CreateAnnotations(identityRoleClaimlong);
            IdentityUserClaimlongEntityType.CreateAnnotations(identityUserClaimlong);
            IdentityUserLoginlongEntityType.CreateAnnotations(identityUserLoginlong);
            IdentityUserRolelongEntityType.CreateAnnotations(identityUserRolelong);
            IdentityUserTokenlongEntityType.CreateAnnotations(identityUserTokenlong);

            AddAnnotation("ProductVersion", "6.0.5");
        }
    }
}
