[package]
name = "anf-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
