name: .NET Build Windows 

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
        project: [Platforms/Anf.Desktop.sln,Platforms/Anf.Web.sln]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef
    - name: Restore dependencies
      run: dotnet restore ${{ matrix.project }}
    - name: Build
      run: dotnet build ${{ matrix.project }} --no-restore 
