name: .NET Build Linux 

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Platforms/Anf.Desktop.sln
    - name: Build
      run: dotnet build Platforms/Anf.Desktop.sln --no-restore 
